//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyDescription("Query and paging extensions for NHibernate")]
[assembly: AssemblyProduct("Querify")]
[assembly: AssemblyVersion("0.8.2")]
[assembly: AssemblyFileVersion("0.8.2")]
[assembly: AssemblyInformationalVersion("0.8.2")]
[assembly: AssemblyCopyright("Copyright (c) Lotpath 2014")]
